# Generated by Django 4.1 on 2022-10-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0004_rename_user_passenger_alter_avatar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='imagen',
        ),
        migrations.AddField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
